### ISSUE TITLE
Do not use this repo's harmonized models until they are fixed

### ISSUE THREAD

**Issue by drewlinsley** [ViCCo-Group/thingsvision#181]
There have now been multiple papers published using this papers implementations of Harmonized models (https://github.com/serre-lab/Harmonization/)

The implementation in this repo has screwed up the preprocessing. No one should use or report results from these model until they are completely fixed and validated.

This issue should also be pinned to this repo and not resolved since multiple papers published at CS conferences have this problem. I know errata are generally not published for CS papers, but problems introduced by this repo -- and left unchecked by many authors -- have led to many incorrect results being published. This is really bad.

In the future the authors of this repo can avoid this kind of problem by benchmarking models against published results. For example, ImageNet performance is published in the original Harmonization paper. The current implementations do not replicate published results.

**Comment by drewlinsley** [comment]
There have now been multiple papers published using this papers implementations of Harmonized models (https://github.com/serre-lab/Harmonization/)

The implementation in this repo has screwed up the preprocessing. No one should use or report results from these until they are fixed.

This issue should also be pinned to this repo and not resolved since multiple papers published at CS conferences have this problem.

In the future the authors of this repo can avoid this kind of problem by benchmarking models against published results. For example, ImageNet performance is published in the original Harmonization paper. The current implementations do not replicate published results.

**Comment by LukasMut** [comment]
@drewlinsley thank you for raising this concern! After @candemircan made a PR to integrate the Harmonized models a while ago, we immediately had @fel-thomas have a look at the implementation (he gave green light!) and IIRC I had a couple of conversations with him and you (mainly him) about the implementation (and, yes, even about the preprocessing) because it was an absolute pain to get anything from your GitHub repo to work. @fel-thomas has write access to `thingsvision` ever since we integrated your models. Perhaps the authors of the Harmonization models should do a better job in making sure that their own models are correctly integrated in a public library ;) 

Anyway, I have no intention to pick up a fight. We will make sure that this is resolved asap (and I think @candemircan's most recent PR does exactly this).

**Comment by drewlinsley** [comment]
Come on this is completely unfair and defensive. All we care about is moving science along. Drop the pretenses and fix this.

**Comment by drewlinsley** [comment]
No intention to pick a fight but you respond like this? Get out of here. This is poor poor behavior.

**Comment by fel-thomas** [comment]
Answering as I have been tagged...

Thank for the answer. However, I want to clarify that the issue originates from the ThingsVision integration, not the Harmonized models repo. The implementation in my repo has been thoroughly validated and matches published results.

I did review the ThingsVision PR in good faith, trusting their preprocessing aligned with our original setup. If bugs remain, they are on their end, not due to my code. That said, I am deeply saddened by the comment about my repo being _"a pain to work with."_ 

Significant effort went into making the Harmonized models reliable, and such statements feel unnecessarily harsh and unfair. 

I’m happy to assist in resolving this, but it’s important to recognize where the responsibility lies. Let’s work constructively to address the issue.

**Comment by martinhebart** [comment]
Hi all,

I very much understand people's sentiments but I think we should - at this
point - focus our efforts on resolving this issue and then have this
discussion later. Would that be ok with you?

Martin



Am Mo., 18. Nov. 2024 um 17:57 Uhr schrieb Thomas Fel <
***@***.***>:

**Comment by LukasMut** [comment]
Just FYI: I will delete any comment that is not in line with how I want us to talk to each other. We are not on X. Let's keep GitHub a safe space.

If you @drewlinsley care so much about "moving science forward" and accuse me of not doing this -- which is funny because the whole reason I am still maintaining this repo is because I want to help our research community thrive and make our (scientific) lives easier --, I am puzzled by the fact that you haven't come across this bug earlier or done a PR yourself.

Again, we are on it (see most recent PR), but I am currently on vacation without a laptop (responding via GitHub mobile because it seems urgent).

**Comment by LukasMut** [comment]
@drewlinsley @fel-thomas everything is fixed and updated!!
